# Be sure to restart your server when you modify this file.
common: &common
  database_username: <%= ENV["DATABASE_USERNAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_secret: <%= ENV["DEVISE_SECRET"] %>

development:
  <<: *common

test:
  <<: *common

staging:
  <<: *common

production:
  <<: *common
