# Be sure to restart your server when you modify this file.
common: &common
  database_username: <%= ENV["DATABASE_USERNAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_secret: <%= ENV["DEVISE_SECRET"] %>
  router_port: <%= ENV['ROUTER_PORT'] %>
  router_host: <%= ENV['ROUTER_HOST'] %>
  router_username: <%= ENV['ROUTER_USERNAME'] %>
  router_password: <%= ENV['ROUTER_PASSWORD'] %>
  nexudus_username: <%= ENV['NEXUDUS_USERNAME'] %>
  nexudus_password: <%= ENV['NEXUDUS_PASSWORD'] %>

development:
  <<: *common

test:
  <<: *common

staging:
  <<: *common

production:
  <<: *common
